version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123 
      POSTGRES_DB: geolocation_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:  
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - API_KEY=${API_KEY}
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=geolocation_db
      - DB_PORT=5432
    networks:
      - app-network
    volumes:
      - .:/app
    command: npm start

volumes:
  db-data:

networks:
  app-network:
